### ISSUE TITLE
Add metadata sink for a file

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#129]
Sink final results to a file

**Comment by GrayFlash** [comment]
```yaml
sinks:
    name: file
    config:
        format: "yaml/json"
        filename: "postgres_food_app_data"
        output-dir: path/to/folder
```

I thought this should be a fine format for `config` with all the necessary info required for the file sink. 
Also, supporting the `json` and `yaml` format is the expected behavior and not some other format, right?? @StewartJingga 

Feel free to add any suggestions/feedback or additional expectations from this sink.
cc: @ravisuhag @mabdh @scortier

**Comment by GrayFlash** [comment]
Also, have thought to keep the format and output-dir fields in config **optional**, and add some default values ourselves.
For eg:
format: json 
output-dir = current

**Comment by mabdh** [comment]
Whatbout we just use filename field and directory could be inferred from that field 
e.g.
```
filename: ./dir/some-dir/postgres_food_app_data
```

**Comment by GrayFlash** [comment]
> What about we just use `filename` field and directory could be inferred from that field?

In this case we can also include the format then?? Cause just having the directory and filename patched together can be confusing if there is no extension at the end?

```
filename: ./dir/some-dir/postgres_food_app_data.json
```

**Comment by ravisuhag** [comment]
and `filename` could be called `path` imo?

**Comment by mabdh** [comment]
@GrayFlash but on the other hand, `json` and `yaml` are just a data format. they don't have to be coupled to the file extension. in this case, i don't think we should restrict file extension to the user but the best practice should be following what the data format is (we let user decide).

**Comment by GrayFlash** [comment]
@mabdh makes sense, so should we have a config like this:
```yaml
config:
    filename: ./dir/some-dir/postgres_food_app_data.json
    format: json
```

Where format is for defining data format and we write the data in the expected format in the whatever file extension user provides??
