### ISSUE TITLE
feat: recipe templating to create multiple recipes with identical config

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#301]
**Is your feature request related to a problem? Please describe.**
I have a multiple recipes with similar configurations. Sample would be:

```
# recipe-1.yaml
source:
  type: kafka
  config:
    broker: "main-broker.com:9092"
sinks:
  - name: console
processors:
  - name: enrich
    config:
      host:  main-broker.com:9092
      owner:  john@example.com

# recipe-2.yaml
source:
  type: kafka
  config:
    broker: "secondary-broker.com:9092"
sinks:
  - name: console
processors:
  - name: enrich
    config:
      host:  secondary-broker.com:9092
      owner:  jane@example.com
```

The only differences between those two are the broker and the owner values. The sample above is relatively simple recipes so replicating it should still be okay. But in my setup, I have a far more complicated recipes which I have to write manually for each of them despite them being identical in structure.

**Describe the solution you'd like**
Meteor to provide a command to run a recipe template.

```
meteor run template.yaml --data data.yaml

# template.yaml
source:
  type: kafka
  config:
    broker: "{{ .broker }}"
sinks:
  - name: console
processors:
  - name: enrich
    config:
      host:  {{ .broker }}
      owner:  {{ .owner }}

# data.yaml
data:
  - broker: main-broker.com:9092
    owner: john@example.com
  - broker: secondary-broker.com:9092
    owner: jane@example.com
```

**Describe alternatives you've considered**
I created a script to receive a yaml and a template to generate multiple recipe files.
So far it is working fine for me, but it would be great if Meteor itself provides this functionality
