### ISSUE TITLE
Meteor bigquery extractor runs for too long

### ISSUE THREAD

**Issue by bsushmith** [odpf/meteor#389]
**Is your feature request related to a problem? Please describe.** 
We have a  big query project where the total number of tables is in a couple of thousands. Whenever we run the big query meteor extractor on this project, we have seen that the meteor cron job takes more than 14hrs - even with the `max_preview_rows` set as zero and table/column profiling set as `false`.

I assume that this is mostly due to the way the [datasets](https://github.com/odpf/meteor/blob/main/plugins/extractors/bigquery/bigquery.go#L129) and [tables](https://github.com/odpf/meteor/blob/main/plugins/extractors/bigquery/bigquery.go#L156) are fetched iteratively one after the other in code. 

**Describe the solution you'd like**
Would like the extractor cron job to run and complete faster than the current time. I can see a couple of approaches to this at present:
1. Fetch datasets and table information concurrently instead of one table after another, with a fixed number(configurable) of workers, or using [pages](https://github.com/googleapis/google-cloud-go/wiki/Iterator-Guidelines)
2. Table metadata information could be fetched from information schema also - as detailed in this [link](https://thedigitalskye.com/2021/02/02/query-table-metadata-easily-in-google-bigquery/) - this might have impact on big query data processing costs. This also requires the BQ service account to have additional access to run jobs.

**Additional context**
Version : `latest` main

**Comment by bsushmith** [comment]
Configuring a max page size for the bigquery extractor should make this considerably faster with minimal effort.

For testing this out, we have deployed a `v0.4.0` meteor patched with the below patch. A bq recipe that used to take around `15 hrs`, got completed in under `1.5 hrs`.




```diff
From 476ebae3aef8cdfb293dc11164dfdd098bffbd82 Mon Sep 17 00:00:00 2001
From: sushmith 
Date: Sat, 12 Nov 2022 16:10:53 +0530
Subject: [PATCH] feat(bigquery): set max page size in iterators in bigquery
 extractor

---
 plugins/extractors/bigquery/bigquery.go | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/plugins/extractors/bigquery/bigquery.go b/plugins/extractors/bigquery/bigquery.go
index 4f9b801..0bea9f8 100644
--- a/plugins/extractors/bigquery/bigquery.go
+++ b/plugins/extractors/bigquery/bigquery.go
@@ -129,6 +129,7 @@ func (e *Extractor) Extract(ctx context.Context, emit plugins.Emit) (err error)
 
 	// Fetch and iterate over datasets
 	it := e.client.Datasets(ctx)
+	it.PageInfo().MaxSize = 100
 	for {
 		ds, err := it.Next()
 		if err == iterator.Done {
@@ -164,6 +165,7 @@ func (e *Extractor) createClient(ctx context.Context) (*bigquery.Client, error)
 // Create big query client
 func (e *Extractor) extractTable(ctx context.Context, ds *bigquery.Dataset, emit plugins.Emit) {
 	tb := ds.Tables(ctx)
+	tb.PageInfo().MaxSize = 100
 	for {
 		table, err := tb.Next()
 		if err == iterator.Done {
@@ -300,6 +302,7 @@ func (e *Extractor) buildPreview(ctx context.Context, t *bigquery.Table) (previe
 	rows := []interface{}{}
 	totalRows := 0
 	ri := t.Read(ctx)
+	ri.PageInfo().MaxSize = 100
 	for totalRows < e.config.MaxPreviewRows {
 		var row []bigquery.Value
 		err = ri.Next(&row)
@@ -361,6 +364,7 @@ func (e *Extractor) getColumnProfile(ctx context.Context, col *bigquery.FieldSch
 	}
 
 	it, err := query.Read(ctx)
+	it.PageInfo().MaxSize = 100
 	if err != nil {
 		return nil, err
 	}
-- 
2.34.1

```

recipe example:

```yaml
name: sample-bq-project-recipe
version: v1beta1
source:
  type: bigquery
  config:
    project_id: sample-project
    service_account_base64: _______base64_encoded_service_account_string_______
sinks:
  - name: compass
    config:
      host: http://localhost:8080
      headers:
        X-Shield-User-Id: meteor
        X-Shield-Email: meteor
      labels:
        dataset: "$properties.attributes.dataset"
        project: "$properties.attributes.project"

processors:
  - name: "enrich"
    config:
      entity: "odpf"
```

**Comment by ravisuhag** [comment]
@bsushmith shall we also make max-size configurable with a default?

**Comment by bsushmith** [comment]
@ravisuhag As a note, this recipe doesn't include some additional bq extraction [options](https://github.com/odpf/meteor/tree/main/plugins/extractors/bigquery#usage) such as

```yaml
    profile_column: true
    collect_table_usage: false
    usage_period_in_day: 7
    usage_project_ids:
      - google-project-id 
      - other-google-project-id
```

Will take those separately.
