### ISSUE TITLE
bug: meteor "new recipe" command is not using latest recipe requirement

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#402]
**Describe the bug**
Current `meteor new` command does not use the latest recipe requirements.

generated-recipe.yaml
```
name: sample
version: v1beta1
source:
  type: kafka
  config:     
    broker: "my-broker:6668"
sinks:
  - name: http
    config:       
      # The url (hostname and route) of the http service
      url: http://localhost:3333
      method: POST
      # Additional HTTP headers, multiple headers value are separated by a comma
      headers:
        X-Other-Header: value1, value2
```

running this get below error
```
ERRO[0000] error running recipe                          duration_ms=0 err="failed to setup extractor: could not initiate extractor \"kafka\": urn scope is required to generate unique urn" recipe=sample records_count=0
ERRO[0000] failed to setup extractor: could not initiate extractor "kafka": urn scope is required to generate unique urn
```

The error is because since version `0.5.0`, meteor introduce new required `source.scope` field on recipe.
This field is needed to make sure asset's `urn` is unique by using `scope` as some sort of namespacing feature.

**To Reproduce**
1. Run `meteor new recipe sample -e kafka -s http > recipe.yaml`
2. Copy printed out recipe to a file (`recipe.yaml`)
3. Run `meteor run recipe.yaml`

**Expected behavior**

### Update `new` command
`meteor new recipe` should include `scope` on the generated recipe. It could also make `scope` as part of required input when running the command. e.g. `--scope=my-scope`.

### Docs updated
Somewhere in the docs, it would be helpful if the new `scope` field is being mentioned so that users are not stuck.
