### ISSUE TITLE
Add metadata extractor for caraml-store

### ISSUE THREAD

**Issue by ravisuhag** [odpf/meteor#73]
- [ ] Add unit tests
- [ ] Add extractor
- [ ] Add README.md in ```plugins/extractors/caramlstore```, defining output
- [ ] Register your extractor ```plugins/extractors/populate.go```
- [ ] Add extractor the extractor list in ```docs/reference/extractor.md```

**Comment by mabdh** [comment]
[feast](https://feast.dev/)

**Comment by sudo-suhas** [comment]
caraml-store: https://github.com/caraml-dev/caraml-store
Core gRPC service def: [caraml-dev/caraml-store@`main/caraml-store-protobuf/.../feast/core/CoreService.proto`](https://github.com/caraml-dev/caraml-store/blob/main/caraml-store-protobuf/src/main/proto/feast/core/CoreService.proto)

**Comment by sudo-suhas** [comment]
CaraML Store does not have any ownership information. @StewartJingga @ravisuhag could you suggest a way to handle this? We won't be able to sync the information into Compass without ownership info.

**Comment by ravisuhag** [comment]
@sudo-suhas I think we can skip that for now. Compass would provide APIs for people to map owner information.

**Comment by sudo-suhas** [comment]
But it would fail to sync:

Example failure from local run:
```
INFO[0000] sinking record to compass record="urn:caramlstore:core.s.ng.feast.golabs.io:ml_feature_table:omakase_id_customer_app_interactions"
ERRO[0000] error running sink        error="error sending data: compass returns 400: {\"code\":3,\"message\":\"no user information\",\"details\":[]}" sink=compass
```

**Comment by ravisuhag** [comment]
@StewartJingga Is owner information is must in Compass APIs? Is shouldn't be right.

**Comment by StewartJingga** [comment]
> @StewartJingga Is owner information is must in Compass APIs? Is shouldn't be, right?

No, it does not require owner information.

But it does require a header (or in grpc a metadata) to identify who makes the request.
In this case, the required header is `X-Shield-User-Id`.

**Sample recipe**
```yaml
sinks:
      - name: compass
        config:
          host: http://compass.golabs.io
          headers:
            X-Shield-User-Id: meteor@odpf.io
            X-Auth-Email: meteor@odpf.io
          labels:
            entity: "$properties.attributes.entity"
            stream: "$properties.attributes.stream"
```
